import { MiniGameConfig, Achievement, FunCardId, FunCard } from './types';

// Using simple SVG icons as components for better visuals
export const Icons = {
  Flag: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M3 2.25a.75.75 0 01.75.75v.54l1.838-.46a9.75 9.75 0 016.725.738l.108.054a8.25 8.25 0 005.58.652l3.109-.732a.75.75 0 01.917.81 47.784 47.784 0 00.005 10.337.75.75 0 01-.574.812l-3.114.733a9.75 9.75 0 01-6.594-.158l-.106-.053a8.25 8.25 0 00-5.69-.717l-2.153.538a.75.75 0 01-.933-.738v-8.29a2.42 2.42 0 00-1.5-.163.75.75 0 11-.348-1.458A3.92 3.92 0 013 2.25zM4.5 4.015v8.726c.745-.13 1.545-.14 2.316.053l2.153.538a9.75 9.75 0 016.724.847l.107.054a8.25 8.25 0 005.58.186 46.26 46.26 0 01-.002-9.256 9.75 9.75 0 01-6.495.69l-3.109.732a8.25 8.25 0 00-5.69-.766l-1.468.367a.75.75 0 01-.116.015z" clipRule="evenodd" />
      <path d="M3 15.75a.75.75 0 01.75.75v5.25a.75.75 0 01-1.5 0v-5.25a.75.75 0 01.75-.75z" />
    </svg>
  ),
  Question: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm11.378-3.917c-.89-.777-2.366-.777-3.255 0a.75.75 0 01-.988-1.129c1.454-1.272 3.776-1.272 5.23 0 1.513 1.324 1.513 3.518 0 4.842a3.75 3.75 0 01-.837.552c-.676.328-1.028.774-1.028 1.152v.75a.75.75 0 01-1.5 0v-.75c0-1.279 1.06-2.107 1.875-2.502.182-.088.351-.199.503-.331.83-.727.83-1.857 0-2.584zM12 18a.75.75 0 100-1.5.75.75 0 000 1.5z" clipRule="evenodd" />
    </svg>
  ),
  Sword: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z" clipRule="evenodd" />
    </svg>
  ),
  Lock: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
       <path fillRule="evenodd" d="M12 1.5a5.25 5.25 0 00-5.25 5.25v3a3 3 0 00-3 3v6.75a3 3 0 003 3h10.5a3 3 0 003-3v-6.75a3 3 0 00-3-3v-3c0-2.9-2.35-5.25-5.25-5.25zm3.75 8.25v-3a3.75 3.75 0 10-7.5 0v3h7.5z" clipRule="evenodd" />
    </svg>
  ),
  Clock: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zM12.75 6a.75.75 0 00-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 000-1.5h-3.75V6z" clipRule="evenodd" />
    </svg>
  ),
  Dumbbell: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M15.75 1.5a.75.75 0 00-.75.75v2.49l-6.75 3.374V7.5a.75.75 0 00-1.5 0v.75a.75.75 0 000 1.5v.75a.75.75 0 000 1.5v.75a.75.75 0 001.5 0v-.636l6.75 3.375v2.49a.75.75 0 001.5 0V1.5a.75.75 0 00-.75-.75zM8.25 1.5a.75.75 0 00-.75.75v2.49L.75 8.114V7.5a.75.75 0 00-1.5 0v.75a.75.75 0 000 1.5v.75a.75.75 0 001.5 0v-.636l6.75 3.375v2.49a.75.75 0 001.5 0V1.5a.75.75 0 00-.75-.75z" clipRule="evenodd" />
       <path d="M5.5 12a.75.75 0 01.75-.75h11.5a.75.75 0 010 1.5H6.25a.75.75 0 01-.75-.75z" />
    </svg>
  ),
  Trophy: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M5.166 2.621v.858c-1.035.148-2.059.33-3.071.543a.75.75 0 00-.584.859 6.753 6.753 0 006.138 5.6 6.73 6.73 0 002.743 1.346A6.707 6.707 0 019.279 15H8.54c-1.036 0-1.875.84-1.875 1.875V19.5h-.75a2.25 2.25 0 00-2.25 2.25c0 .414.336.75.75.75h15a.75.75 0 00.75-.75 2.25 2.25 0 00-2.25-2.25h-.75v-2.625c0-1.036-.84-1.875-1.875-1.875h-.739a6.706 6.706 0 01-1.112-3.173 6.73 6.73 0 002.743-1.347 6.753 6.753 0 006.139-5.6.75.75 0 00-.585-.858 47.077 47.077 0 00-3.07-.543V2.62a.75.75 0 00-.658-.744 49.22 49.22 0 00-6.093-.377c-2.063 0-4.096.128-6.093.377a.75.75 0 00-.657.744zm0 2.629c0 1.196.312 2.32.857 3.294A5.266 5.266 0 013.16 5.337a45.6 45.6 0 012.006-.343v.256zm13.5 0v-.256c.674.1 1.343.214 2.006.343a5.265 5.265 0 01-2.863 3.214 6.383 6.383 0 01.857-3.294z" clipRule="evenodd" />
    </svg>
  ),
  Settings: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
       <path fillRule="evenodd" d="M11.078 2.25c-.917 0-1.699.663-1.85 1.567L9.05 4.889c-.02.12-.115.26-.297.348a7.493 7.493 0 00-.986.57c-.166.115-.334.126-.45.083L6.3 5.508a1.875 1.875 0 00-2.282.819l-.922 1.597a1.875 1.875 0 00.432 2.385l.84.692c.095.078.17.229.154.43a7.598 7.598 0 000 1.139c.015.2-.059.352-.153.43l-.841.692a1.875 1.875 0 00-.432 2.385l.922 1.597a1.875 1.875 0 002.282.818l1.019-.382c.115-.043.283-.031.45.082.312.214.641.405.985.57.182.088.277.228.297.35l.178 1.071c.151.904.933 1.567 1.85 1.567h1.844c.916 0 1.699-.663 1.85-1.567l.178-1.072c.02-.12.114-.26.297-.349.344-.165.673-.356.985-.57.167-.114.335-.125.45-.082l1.02.382a1.875 1.875 0 002.28-.819l.923-1.597a1.875 1.875 0 00-.432-2.385l-.84-.692c-.095-.078-.17-.229-.154-.43a7.614 7.614 0 000-1.139c-.016-.2.059-.352.153-.43l.84-.692c.708-.582.891-1.59.433-2.385l-.922-1.597a1.875 1.875 0 00-2.282-.818l-1.02.382c-.114.043-.282.031-.449-.083a7.49 7.49 0 00-.985-.57c-.183-.087-.277-.227-.297-.348l-.179-1.072a1.875 1.875 0 00-1.85-1.567h-1.843zM12 15.75a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5z" clipRule="evenodd" />
    </svg>
  ),
  Exit: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm-1.72 6.97a.75.75 0 10-1.06 1.06L10.94 12l-1.72 1.72a.75.75 0 101.06 1.06L12 13.06l1.72 1.72a.75.75 0 101.06-1.06L13.06 12l1.72-1.72a.75.75 0 10-1.06-1.06L12 10.94l-1.72-1.72z" clipRule="evenodd" />
    </svg>
  ),
  // New Practice Icons
  Play: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M4.5 5.653c0-1.426 1.529-2.33 2.779-1.643l11.54 6.348c1.295.712 1.295 2.573 0 3.285L7.28 19.991c-1.25.687-2.779-.217-2.779-1.643V5.653z" clipRule="evenodd" />
    </svg>
  ),
  Pause: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M6.75 5.25a.75.75 0 01.75-.75H9a.75.75 0 01.75.75v13.5a.75.75 0 01-.75.75H7.5a.75.75 0 01-.75-.75V5.25zm7.5 0a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v13.5a.75.75 0 01-.75.75h-1.5a.75.75 0 01-.75-.75V5.25z" clipRule="evenodd" />
    </svg>
  ),
  Restart: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M4.755 10.059a7.5 7.5 0 0112.548-3.364l1.903 1.903h-3.183a.75.75 0 100 1.5h4.992a.75.75 0 00.75-.75V4.356a.75.75 0 00-1.5 0v3.18l-1.9-1.9A9 9 0 003.306 9.67a.75.75 0 101.45.388zm15.408 3.352a.75.75 0 00-.919.53 7.5 7.5 0 01-12.548 3.364l-1.902-1.903h3.183a.75.75 0 000-1.5H2.984a.75.75 0 00-.75.75v4.992a.75.75 0 001.5 0v-3.18l1.9 1.9a9 9 0 0015.059-4.035.75.75 0 00-.53-.918z" clipRule="evenodd" />
    </svg>
  ),
  Chart: ({ className }: { className?: string }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M3 3.75A.75.75 0 013.75 3h16.5a.75.75 0 010 1.5H4.5v15h15.75a.75.75 0 010 1.5H3.75A.75.75 0 013 20.25V3.75z" clipRule="evenodd" />
      <path d="M8.25 16.5a.75.75 0 01-.75-.75v-4.5a.75.75 0 011.5 0v4.5a.75.75 0 01-.75.75zm4.5 0a.75.75 0 01-.75-.75v-7.5a.75.75 0 011.5 0v7.5a.75.75 0 01-.75.75zm4.5 0a.75.75 0 01-.75-.75V9a.75.75 0 011.5 0v6.75a.75.75 0 01-.75.75z" />
    </svg>
  )
};

export const MINI_GAMES: MiniGameConfig[] = [
  { id: 'math', name: 'Math Rush', type: 'TIMED', icon: '🧮', description: 'Solve 3 equations!' },
  { id: 'mash', name: 'Power Mash', type: 'TIMED', icon: '💥', description: 'Mash to fill the bar!' },
  { id: 'stroop', name: 'Stroop Test', type: 'ACCURACY', icon: '🎨', description: 'Pick the COLOR, 5 times!' },
  { id: 'reaction', name: 'Reaction', type: 'TIMED', icon: '⚡', description: 'Click on Green (<350ms)!' },
  { id: 'memory', name: 'Matrix', type: 'ACCURACY', icon: '🧠', description: 'Tap tiles in order!' },
  { id: 'lockpick', name: 'Lock Pick', type: 'TIMED', icon: '🔐', description: 'Tap when green! (x3)' },
  { id: 'password', name: 'Scramble', type: 'TIMED', icon: '⌨️', description: 'Type the code!' },
  { id: 'burst', name: 'Aim Lab', type: 'SCORE', icon: '🎯', description: 'Hit 5 moving targets!' },
  { id: 'sequence', name: '1-2-3', type: 'TIMED', icon: '🔢', description: 'Click in order!' },
  { id: 'mousemaze',    name: "Don't Touch Red",  type: 'TIMED', icon: '🖱️', description: 'Navigate without touching red!' },
  { id: 'gravitymaze', name: 'Gravity Maze',  type: 'TIMED',    icon: '🔄', description: 'Flip gravity to reach the star!' },
  { id: 'rhythmcopy',  name: 'Rhythm Copy',   type: 'ACCURACY', icon: '🥁', description: 'Watch and copy the beat!' },
  { id: 'oddchar',     name: 'Odd One Out',   type: 'TIMED',    icon: '🔍', description: 'Find the different character!' },
];

export const MINI_GAME_ZH_META: Record<string, { name: string; description: string }> = {
  math: { name: '数学冲刺', description: '在限时内解出 3 道算式。' },
  mash: { name: '动力连点', description: '疯狂点击，把能量条顶满。' },
  stroop: { name: '色词冲突', description: '选出文字真实颜色，连对 5 次。' },
  reaction: { name: '反应测试', description: '变绿瞬间点击，拼最快反应。' },
  memory: { name: '矩阵记忆', description: '记住闪烁顺序并按序点回去。' },
  lockpick: { name: '开锁挑战', description: '指针进绿色区时点击，连续成功。' },
  password: { name: '密码乱序', description: '在乱序键盘里输入正确密码。' },
  burst: { name: '准星打靶', description: '快速命中不断缩小的目标。' },
  sequence: { name: '数字连点', description: '按 1 到 N 的顺序点击数字。' },
  mousemaze: { name: '别碰红区', description: '沿白色通道移动，碰红即失败。' },
  gravitymaze: { name: '重力迷宫', description: '点击翻转重力，躲障碍到终点。' },
  rhythmcopy: { name: '节奏复刻', description: '观察后复刻同样的节奏序列。' },
  oddchar: { name: '找不同字', description: '在字符阵列中找出唯一异类。' },
};

export const WIN_PATTERNS = [
  [0, 1, 2], [3, 4, 5], [6, 7, 8], // Rows
  [0, 3, 6], [1, 4, 7], [2, 5, 8], // Cols
  [0, 4, 8], [2, 4, 6]             // Diagonals
];

export const MINI_GAME_TRANSLATIONS = {
  en: {
    mash_instr: "MASH FAST!",
    stroop_instr: "Color of text?",
    wait: "WAIT...",
    click: "CLICK!",
    too_early: "TOO EARLY!",
    too_slow: "TOO SLOW!",
    type_code: "Code:",
    lock_instr: "Tap on Green!",
    find: "Find",
    repeat: "Watch...",
    repeat_go: "Repeat!",
    sequence_instr: "Order:",
    burst_instr: "Targets:",
    good_job: "Success!",
    try_again: "Failed!",
    clr: "C",
    score: "Score",
    retry: "Retry",
    matrix_order: "In sequence!",
    oddone_instr: "Find the odd one!",
    maze_start: "Move cursor to the green circle",
    maze_playing: "Don't touch red!",
    maze_start_touch: "Drag finger to the green circle",
    maze_playing_touch: "Stay on the white path!",
    maze_hint: "Stay on the white path",
    tutorial_hint_math: "Hint: Correct answer is highlighted",
    tutorial_hint_goal: "Goal",
    tutorial_hint_stroop: "Match this color!",
    tutorial_hint_reaction: "Wait for green...",
    tutorial_hint_lockpick: "Tap when needle reaches green",
    tutorial_hint_burst: "Click!",
    tutorial_hint_gravity: "Click = flip gravity",
    gravity_start: "Click to start",
    gravity_instr: "Click to flip gravity!",
    gravity_retry: "Click to retry",
    skill_freeze: "FREEZE",
    skill_used: "USED",
    skill_steal: "STEAL",
    skill_duel: "DUEL",
    duel_title: "DUEL!",
    duel_pick_instr: "Pick an empty cell to race —",
    duel_opp_picking: "Opponent is picking a cell...",
    duel_racing: "DUEL RACING",
    duel_cell: "Cell",
    skill_pick_title: "EQUIP SKILLS",
    skill_pick_instr: "Choose 2 skills to bring into battle. Your opponent can't see your picks.",
    skill_pick_confirm: "CONFIRM",
    skill_pick_waiting: "Waiting for opponent...",
    rhythm_start: "Watch & copy the beat",
    rhythm_watch: "Watch...",
    rhythm_play: "Your turn!",
    rhythm_retry: "Wrong beat! Retry",
    oddchar_start: "Find the odd character",
    oddchar_find: "Spot it!",
    oddchar_retry: "Time's up! Retry",
  },
  zh: {
    mash_instr: "疯狂点击！",
    stroop_instr: "字的颜色是？",
    wait: "等待...",
    click: "点击！",
    too_early: "太早了！",
    too_slow: "太慢了！",
    type_code: "输入密码：",
    lock_instr: "绿色时点击！",
    find: "找到",
    repeat: "观察...",
    repeat_go: "复原！",
    sequence_instr: "按顺序点击：",
    burst_instr: "剩余目标：",
    good_job: "成功！",
    try_again: "失败！",
    clr: "清",
    score: "得分",
    retry: "重试",
    matrix_order: "按顺序！",
    oddone_instr: "找不同！",
    maze_start: "将鼠标移到绿色圆圈",
    maze_playing: "别碰红线！",
    maze_start_touch: "拖动手指到绿色圆圈",
    maze_playing_touch: "沿白色通道前进！",
    maze_hint: "保持在白色通道内",
    tutorial_hint_math: "提示：高亮的是正确答案",
    tutorial_hint_goal: "目标",
    tutorial_hint_stroop: "选这个颜色！",
    tutorial_hint_reaction: "等变绿再点...",
    tutorial_hint_lockpick: "指针到绿色区再点击",
    tutorial_hint_burst: "点击！",
    tutorial_hint_gravity: "点击可反转重力",
    gravity_start: "点击开始",
    gravity_instr: "点击反转重力！",
    gravity_retry: "点击重试",
    skill_freeze: "冻结",
    skill_used: "已用",
    skill_steal: "夺旗",
    skill_duel: "决斗",
    duel_title: "决斗！",
    duel_pick_instr: "选择一个空格开始决斗 —",
    duel_opp_picking: "对手正在选择格子……",
    duel_racing: "决斗进行中",
    duel_cell: "第",
    skill_pick_title: "选择技能",
    skill_pick_instr: "选择2个带入对局的技能，对方看不到你的选择。",
    skill_pick_confirm: "确认",
    skill_pick_waiting: "等待对手选择……",
    rhythm_start: "观察并复制节奏",
    rhythm_watch: "观察中...",
    rhythm_play: "轮到你了！",
    rhythm_retry: "打错了！重试",
    oddchar_start: "找出不同的字",
    oddchar_find: "快找！",
    oddchar_retry: "超时！重试",
  }
};

export const FUN_CARDS: FunCard[] = [
  { id: 'EGG'       as FunCardId, icon: '🥚', nameKey: 'fun_egg',       descKey: 'fun_egg_desc' },
  { id: 'SHUFFLE'   as FunCardId, icon: '🔀', nameKey: 'fun_shuffle',   descKey: 'fun_shuffle_desc' },
  { id: 'ZAP'       as FunCardId, icon: '⚡', nameKey: 'fun_zap',       descKey: 'fun_zap_desc' },
  { id: 'HARD_MODE' as FunCardId, icon: '🔥', nameKey: 'fun_hard_mode', descKey: 'fun_hard_mode_desc' },
  { id: 'FLIP'      as FunCardId, icon: '🙃', nameKey: 'fun_flip',      descKey: 'fun_flip_desc' },
  { id: 'BOMB'      as FunCardId, icon: '💣', nameKey: 'fun_bomb',      descKey: 'fun_bomb_desc' },
  { id: 'REROLL'    as FunCardId, icon: '🎲', nameKey: 'fun_reroll',    descKey: 'fun_reroll_desc' },
  { id: 'LEECH'     as FunCardId, icon: '🧲', nameKey: 'fun_leech',     descKey: 'fun_leech_desc' },
  { id: 'ICE'       as FunCardId, icon: '❄️', nameKey: 'fun_ice',       descKey: 'fun_ice_desc' },
  { id: 'SWAP'      as FunCardId, icon: '🔄', nameKey: 'fun_swap',      descKey: 'fun_swap_desc' },
];

export const TRANSLATIONS = {
  en: {
    menu_online: "ONLINE BATTLE",
    menu_solo: "TIME ATTACK",
    menu_practice: "PRACTICE GYM",
    menu_achievements: "ACHIEVEMENTS",
    menu_stats: "STATISTICS",
    menu_account: "ACCOUNT",
    menu_subtitle: "COMPETITIVE ARENA",
    
    online_host: "Host Game",
    online_host_desc: "Create a room code.",
    online_join: "Join Game",
    online_join_desc: "Enter code.",
    online_create: "CREATE",
    online_join_btn: "JOIN",
    online_waiting: "Waiting for opponent...",
    online_connecting: "Connecting...",
    conn_lost_title: "CONNECTION LOST",
    conn_lost_desc: "The match link was interrupted.",
    conn_reconnecting_title: "RECONNECTING",
    conn_reconnecting_desc: "Trying to restore the match...",
    conn_waiting_title: "WAITING FOR OPPONENT",
    conn_waiting_desc: "Opponent disconnected. Keeping the match state warm for a reconnect.",
    conn_signal_failed: "Cannot reach signaling server. Check network/VPN, then retry.",
    conn_attempt: "Attempt",
    conn_exit_menu: "EXIT TO MENU",
    net_quality: "NET",
    net_rtt: "RTT",
    net_jitter: "JIT",
    net_loss: "LOSS",
    net_revision: "REV",
    net_phase: "PHASE",
    net_phase_waiting: "WAIT",
    net_phase_skills: "SKILL",
    net_phase_rps: "RPS",
    net_phase_playing: "PLAY",
    net_phase_result: "RESULT",
    online_instruction: "Open this URL in a New Tab to simulate Player 2.",
    online_guide_open: "Guide",
    online_guide_intro: "This walkthrough appears on your first visit to online battle. You can reopen it anytime from the top-right button.",
    online_guide_step: "Step",
    online_guide_skip: "Skip",
    online_guide_back: "Back",
    online_guide_next: "Next",
    online_guide_done: "Let's Play",
    online_guide_1_title: "Pick Your Match Type First",
    online_guide_1_body: "Standard Mode is the clean competitive ruleset. Fun Mode keeps the same win condition but adds chaos cards after captures.",
    online_guide_1_hint: "If you are learning the game, start with Standard so you can focus on the board, skills, and mini-games.",
    online_guide_2_title: "Create a Room or Enter a Code",
    online_guide_2_body: "Host creates a new 4-digit room. Join lets you type a 4-digit code directly, and invite links can drop you into a room automatically.",
    online_guide_2_hint: "After you host, the waiting screen gives you a Copy Invite Link button so friends can join without typing the code.",
    online_guide_3_title: "Share the Invite Link",
    online_guide_3_body: "After hosting, use Copy Invite Link in the waiting screen and send it to your friend. Opening that link lands them directly in your room.",
    online_guide_3_hint: "If link opening is blocked, your friend can still join manually with the same 4-digit room code.",
    online_guide_4_title: "Know What Happens After Matchmaking",
    online_guide_4_body: "Once both players connect, you draft 2 skills, play a best-of-3 Rock-Paper-Scissors, and then start racing mini-games on the 3×3 board.",
    online_guide_4_hint: "Three in a row wins instantly. If the board fills up first, whoever owns more cells wins.",
    online_tutorial_label: "Tutorial Match",
    online_tutorial_button: "Play Guided Bot Match",
    online_tutorial_desc: "Start a scripted beginner duel against a slowed-down bot. It teaches the board, freeze, and steal flow step by step.",
    online_tutorial_exit: "Exit Tutorial",
    online_tutorial_replay: "Replay Tutorial",
    online_tutorial_player_name: "Rookie",
    online_tutorial_bot_name: "Coach Bot",
    online_tutorial_step_1_title: "Take the Center Cell",
    online_tutorial_step_1_body: "Start by clicking the glowing center cell. In GridRush, the board only changes when someone clears that cell's mini-game.",
    online_tutorial_step_2_title: "Mini-Games Decide Ownership",
    online_tutorial_step_2_body: "Finish this mini-game to capture the center. Tutorial hints are enabled here, so follow the highlights and clear it confidently.",
    online_tutorial_step_3_title: "Watch the Opponent Move",
    online_tutorial_step_3_body: "The bot is now claiming the top-left cell. Online matches are simultaneous, so you must keep reading the whole board instead of tunnel-visioning one tile.",
    online_tutorial_step_4_title: "Use Freeze at the Right Time",
    online_tutorial_step_4_body: "The bot is racing for the top-right cell. Press your highlighted Freeze skill now to stop its input and buy time.",
    online_tutorial_step_5_title: "Race Into the Active Cell",
    online_tutorial_step_5_body: "Good. Now click the glowing top-right cell and win its mini-game before the bot can recover. Shared cells are direct races.",
    online_tutorial_step_6_title: "Steal an Enemy-Owned Cell",
    online_tutorial_step_6_body: "The bot already owns the top-left cell. Click that glowing enemy tile to trigger a Steal attempt and force a contest.",
    online_tutorial_step_7_title: "Defend Creates a Real Contest",
    online_tutorial_step_7_body: "The bot has defended, so both of you are now fighting over the same cell. When your own cell is being stolen, you can tap DEFEND, but if your current race is more valuable you can also skip defending.",
    online_tutorial_step_8_title: "Tutorial Complete",
    online_tutorial_step_8_body: "You just learned the core online loop: capture open cells, freeze a race, and steal a defended enemy tile. You are ready for real matches.",
    invite_copy_link: "Copy Invite Link",
    invite_link_copied: "\u2713 Copied!",

    game_steal: "STEAL",
    game_enemy: "Enemy",
    game_you: "YOU",
    game_ready: "Steal Ready",
    game_no_steal: "No Steals",
    game_playing: "PLAYING CELL",
    game_rematch: "PLAY AGAIN",
    game_rematch_request_sent: "REQUEST SENT...",
    game_rematch_invite: "OPPONENT INVITED A REMATCH",
    game_rematch_accept: "ACCEPT",
    game_rematch_decline: "DECLINE",
    game_rematch_wait_host: "WAITING FOR HOST...",
    game_rematch_declined: "REMATCH DECLINED",
    
    msg_win: "YOU WIN!",
    msg_lose: "OPPONENT WINS!",
    msg_draw: "DRAW!",
    msg_challenge_complete: "CHALLENGE COMPLETE!",
    msg_steal_attack: "BASE UNDER ATTACK!",
    msg_steal_doing: "STEALING...",
    msg_steal_attack_desc: "Opponent is stealing Cell {cell}! Tap DEFEND to contest, or ignore if your current race matters more.",
    msg_steal_doing_desc: "Stealing Cell {cell} from opponent!",
    msg_defend: "DEFEND",

    rules_title: "How to Play",
    rules_intro: "GridRush is not turn-based tic-tac-toe. You win cells by beating mini-games faster than the other player.",
    rules_goal: "Win instantly with 3 cells in a row, or win on points if all 9 cells are claimed.",
    rules_quick_title: "30-Second Quick Start",
    rules_quick_1: "Blue is P1 and red is P2. Empty cells can be challenged freely; enemy-owned cells require a Steal.",
    rules_quick_2: "Click a '?' cell to enter that cell's mini-game. The first player to clear it claims that cell immediately.",
    rules_quick_3: "You and your opponent can race different cells at the same time, so keep watching the whole board.",
    rules_quick_4: "You may leave a challenge at any time, but canceling a Steal puts your Steal on a 20-second cooldown.",
    rules_flow_title: "How an Online Match Flows",
    rules_flow_1: "Before the board opens, both players secretly draft 2 out of the 3 core skills.",
    rules_flow_2: "Then you play a best-of-3 Rock-Paper-Scissors. The loser starts the real match frozen for 2 seconds.",
    rules_flow_3: "During the board phase, clearing a mini-game immediately captures that cell for you.",
    rules_flow_4: "If the owner presses DEFEND within 5 seconds of a Steal, both players contest the same cell until one clears it first.",
    rules_penalty_title: "Failure and Penalties",
    rules_penalty_1: "Fail the same cell 3 times in a row and you are locked out of that cell for 10 seconds.",
    rules_penalty_2: "If you go AFK, disconnect for too long, or stay inside one challenge too long, the game removes you from that cell.",
    rules_skills_intro: "Each online match lets you secretly draft 2 of the 3 core skills.",
    rules_steal: "If you drafted Steal, you may use it once by entering an enemy-owned cell. If the owner answers in time, both of you race for that cell.",
    rules_freeze: "If you drafted Freeze, you may use it once to block the opponent's input for 2 seconds.",
    rules_duel: "If you drafted Duel, you may use it once to force both players into the same empty cell. The faster player takes it.",
    rules_fun_title: "Fun Mode",
    rules_fun_desc: "Fun Mode keeps the normal win conditions but adds chaos cards when you capture cells, including blackout, reroll, bomb, flip, and other swing effects.",
    rules_tips_title: "Beginner Tips",
    rules_tip_1: "For your first few matches, prioritize open center and corner cells before attempting risky steals.",
    rules_tip_2: "Do not brute-force one hard cell into the 3-failure penalty. Switch targets and come back later.",
    rules_tip_3: "Freeze and Duel are strongest when they stop an enemy line or swing a close endgame.",
    
    settings_title: "SETTINGS",
    settings_lang: "Language / 语言",
    settings_theme: "Theme",
    settings_sound: "Sound Effects",
    settings_music: "Music",
    settings_data: "Clear Data",
    settings_data_desc: "Reset all achievements and stats",
    settings_reset: "RESET",
    settings_close: "Close",

    account_sign_in: "SIGN IN",
    account_sign_up: "SIGN UP",
    account_create_account: "CREATE ACCOUNT",
    account_sign_out: "SIGN OUT",
    account_email: "EMAIL",
    account_password: "PASSWORD",
    account_nickname: "NICKNAME",
    account_nickname_placeholder: "Your display name",
    account_nickname_too_short: "Nickname must be at least 2 characters.",
    account_guest_desc: "Save stats to the cloud and use the same profile on multiple devices.",
    account_connected: "Cloud account connected",
    account_local_only: "LOCAL ONLY",
    account_syncing: "SYNCING...",
    account_synced: "SYNCED",
    account_sync_error: "SYNC FAILED",
    account_sync_now: "SYNC NOW",
    account_last_sync: "Last Sync",
    account_save_profile: "SAVE PROFILE",
    account_no_nickname: "Unnamed Pilot",
    account_working: "WORKING...",
    account_env_missing: "Supabase env not configured",
    account_env_missing_desc: "Create .env.local from .env.example and fill in your project URL plus anon key.",
    account_verify_email: "Registration submitted. Check your email for the confirmation link.",
    account_signed_out: "Signed out. Local stats stay on this device.",

    ach_title: "ACHIEVEMENTS",
    ach_locked: "Locked",
    ach_progress: "Progress",

    // Stats dashboard
    stats_title: "STATISTICS",
    stats_online_overview: "ONLINE OVERVIEW",
    stats_online_matches: "Matches",
    stats_online_wins: "Wins",
    stats_online_losses: "Losses",
    stats_online_draws: "Draws",
    stats_rps_title: "RPS ANALYTICS",
    stats_rps_round_win_rate: "Round Win Rate",
    stats_rps_series_win_rate: "Series Win Rate",
    stats_rps_rounds: "Rounds Won",
    stats_rps_series: "Series Won",
    stats_rps_draws: "Draws",
    stats_global_title: "CAREER",
    stats_games_played: "Games Played",
    stats_best_solo: "Best Solo",
    stats_ach_unlocked: "Achievements",
    stats_practice_records: "Practice Records",
    stats_action_breakdown: "ACTION BREAKDOWN",
    stats_steals: "Steals",
    stats_defends: "Defends",
    stats_freezes: "Freezes",
    stats_duel_wins: "Duel Wins",
    stats_fun_cards_used: "Fun Cards Used",
    stats_solo_bests: "SOLO BESTS",
    stats_recent_matches: "RECENT ONLINE MATCHES",
    stats_recent_empty: "No online match data yet.",
    stats_result_win: "WIN",
    stats_result_lose: "LOSE",
    stats_result_draw: "DRAW",
    stats_mode_standard: "STANDARD",
    stats_mode_fun: "FUN",
    stats_current_streak: "Current Streak",
    stats_recent_trend: "Recent Form",
    stats_best_streak: "Best Win Streak",
    stats_actions_per_match: "Actions / Match",
    stats_mode_split: "MODE SPLIT",
    stats_pick_distribution: "PICK DISTRIBUTION",
    stats_pick_rock: "Rock",
    stats_pick_paper: "Paper",
    stats_pick_scissors: "Scissors",

    exit_game: "Quit",
    level_progress: "Level",

    // Practice Mode
    prac_search: "Search games...",
    prac_filter_all: "ALL",
    prac_filter_timed: "TIMED",
    prac_filter_score: "SCORE",
    prac_filter_accuracy: "ACCURACY",
    prac_pb: "PB:",
    prac_no_pb: "None",
    prac_config_title: "Configuration",
    prac_diff: "Difficulty",
    prac_diff_easy: "EASY",
    prac_diff_normal: "NORMAL",
    prac_diff_hard: "HARD",
    prac_diff_expert: "EXPERT",
    prac_preset_battle: "Battle Preset",
    prac_preset_desc: "Use standard online battle settings",
    prac_tutorial: "Tutorial Hints",
    prac_start: "START PRACTICE",
    prac_paused: "PAUSED",
    prac_resume: "RESUME",
    prac_restart: "RESTART",
    prac_quit: "QUIT",
    prac_res_success: "COMPLETE!",
    prac_res_fail: "FAILED",
    prac_new_record: "NEW RECORD!",
    prac_history: "Recent History",

    // Skills
    skill_steal: "STEAL",
    skill_freeze: "FREEZE",
    skill_duel: "DUEL",
    skill_used: "USED",
    duel_title: "DUEL!",
    duel_pick_instr: "Pick an empty cell to race —",
    duel_opp_picking: "Opponent is picking a cell...",
    duel_racing: "DUEL RACING",
    duel_cell: "Cell",
    skill_pick_title: "EQUIP SKILLS",
    skill_pick_instr: "Choose 2 skills to bring into battle. Your opponent can't see your picks.",
    skill_pick_confirm: "CONFIRM",
    skill_pick_waiting: "Waiting for opponent...",
    // Rock-Paper-Scissors
    rps_title: "ROCK · PAPER · SCISSORS",
    rps_instr: "Best of 3 — winner gets a 2-second head start!",
    rps_round: "Round",
    rps_you: "YOU",
    rps_opp: "OPP",
    rps_rock: "Rock",
    rps_paper: "Paper",
    rps_scissors: "Scissors",
    rps_you_win: "You win the round!",
    rps_you_lose: "Opponent wins the round.",
    rps_draw: "Draw!",
    rps_you_picked: "Your pick is in — waiting...",
    rps_headstart_win: "🎉 You go first! +2s head start",
    rps_headstart_lose: "Opponent goes first. Get ready!",
    rps_headstart_draw: "It's a tie — starting together!",
    rps_waiting: "Waiting for opponent...",
    // Solo Difficulty Picker
    solo_diff_title: "SELECT DIFFICULTY",
    solo_diff_instr: "Complete all 13 mini-games in order, as fast as you can.",
    solo_diff_easy: "Easy",
    solo_diff_normal: "Normal",
    solo_diff_hard: "Hard",
    solo_diff_expert: "Expert",
    solo_diff_desc_easy: "Relaxed challenge, great for learning",
    solo_diff_desc_normal: "A fair test of skill",
    solo_diff_desc_hard: "Tough — mistakes cost time",
    solo_diff_desc_expert: "Not for the faint of heart",
    solo_diff_start: "START",
    solo_diff_back: "Back",
    solo_diff_best: "Best:",

    // Mode selector
    online_mode_label: "GAME MODE",
    std_mode: "STANDARD",
    std_mode_desc: "Classic strategy — no power-ups.",
    fun_mode: "FUN MODE",
    fun_mode_desc: "Capture cells to earn random power-up cards!",

    // Fun mode in-game
    fun_mode_badge: "🎉 FUN",
    fun_card_drawn: "Card Drawn!",
    fun_card_use: "USE",
    fun_blinded: "BLINDED!",
    fun_flipped: "FLIPPED!",
    fun_hard: "NIGHTMARE!",

    // Fun card names / descriptions
    fun_egg: "Blackout",
    fun_egg_desc: "Blind opponent's grid for 5 seconds",
    fun_shuffle: "Shuffle",
    fun_shuffle_desc: "Randomize all unclaimed mini-games",
    fun_zap: "Zap",
    fun_zap_desc: "Knock opponent out of their current cell",
    fun_hard_mode: "Nightmare",
    fun_hard_mode_desc: "Force EXPERT difficulty on opponent for 15s",
    fun_flip: "Flip",
    fun_flip_desc: "Flip opponent's screen upside-down for 5s",
    fun_bomb: "Bomb",
    fun_bomb_desc: "Reset a random opponent-owned cell to neutral",
    fun_reroll: "Reroll",
    fun_reroll_desc: "Change opponent's active cell to a random different mini-game",
    fun_leech: "Leech",
    fun_leech_desc: "Instantly claim one random unclaimed cell",
    fun_ice: "Ice",
    fun_ice_desc: "Freeze opponent for 3.5 seconds",
    fun_swap: "Swap",
    fun_swap_desc: "Swap one of your cells with one of the opponent's",
  },
  zh: {
    menu_online: "在线对战",
    menu_solo: "竞速模式",
    menu_practice: "练习道场",
    menu_achievements: "挑战成就",
    menu_stats: "数据统计",
    menu_account: "账号",
    menu_subtitle: "竞技场",

    online_host: "创建房间",
    online_host_desc: "生成一个房间代码。",
    online_join: "加入房间",
    online_join_desc: "输入房间代码。",
    online_create: "创建",
    online_join_btn: "加入",
    online_waiting: "等待对手加入...",
    online_connecting: "连接中...",
    conn_lost_title: "连接已断开",
    conn_lost_desc: "对局连接已中断。",
    conn_reconnecting_title: "正在重连",
    conn_reconnecting_desc: "正在尝试恢复这场对局...",
    conn_waiting_title: "等待对手重连",
    conn_waiting_desc: "对手已断开，当前正在保留对局状态等待其恢复连接。",
    conn_signal_failed: "无法连接信令服务器。请检查网络或 VPN 后重试。",
    conn_attempt: "尝试",
    conn_exit_menu: "返回菜单",
    net_quality: "网络",
    net_rtt: "延迟",
    net_jitter: "抖动",
    net_loss: "丢包",
    net_revision: "版本",
    net_phase: "阶段",
    net_phase_waiting: "等待",
    net_phase_skills: "选技",
    net_phase_rps: "猜拳",
    net_phase_playing: "对局",
    net_phase_result: "结算",
    online_instruction: "在浏览器新标签页打开此链接以模拟玩家2。",
    online_guide_open: "引导",
    online_guide_intro: "这个引导会在你第一次进入在线对战时出现一次，之后也可以随时点右上角按钮重新打开。",
    online_guide_step: "步骤",
    online_guide_skip: "跳过",
    online_guide_back: "上一步",
    online_guide_next: "下一步",
    online_guide_done: "开始对战",
    online_guide_1_title: "先选对战模式",
    online_guide_1_body: "标准模式是纯竞技规则；娱乐模式保留相同胜负条件，但占格后会追加混乱卡牌效果。",
    online_guide_1_hint: "第一次玩建议先从标准模式开始，先熟悉棋盘、技能和小游戏节奏。",
    online_guide_2_title: "创建房间或输入房间号",
    online_guide_2_body: "创建会生成一个 4 位房间号；加入则可以直接输入 4 位代码。好友邀请链接也会把你自动带进对应房间。",
    online_guide_2_hint: "你创建房间后，等待界面里会有“复制邀请链接”按钮，发给好友后对方不需要手动输码。",
    online_guide_3_title: "分享邀请链接",
    online_guide_3_body: "创建房间后，在等待界面点击“复制邀请链接”发给好友。对方打开链接后会直接进入你的房间。",
    online_guide_3_hint: "如果链接无法直接打开，好友也可以手动输入同一个 4 位房间号加入。",
    online_guide_4_title: "匹配成功后会发生什么",
    online_guide_4_body: "双方连接成功后，会先秘密选 2 个技能，再进行三局两胜猜拳，然后才进入 3×3 棋盘抢格阶段。",
    online_guide_4_hint: "率先连成三格可直接获胜；若棋盘先占满，则占格更多的一方获胜。",
    online_tutorial_label: "新手引导赛",
    online_tutorial_button: "和机器人打一局引导赛",
    online_tutorial_desc: "开始一场脚本化新手对局。机器人会放慢节奏，并一步步教你学会抢格、冻结和抢夺。",
    online_tutorial_exit: "退出教程",
    online_tutorial_replay: "重开教程",
    online_tutorial_player_name: "新手玩家",
    online_tutorial_bot_name: "教练机器人",
    online_tutorial_step_1_title: "先拿下中心格",
    online_tutorial_step_1_body: "先点击发光的中心格。在 GridRush 里，棋盘变化不是轮流下子，而是谁先通关小游戏，谁就拿到那一格。",
    online_tutorial_step_2_title: "小游戏决定归属",
    online_tutorial_step_2_body: "完成这个小游戏来占下中心格。教程赛里小游戏提示已开启，跟着高亮走就能稳稳过关。",
    online_tutorial_step_3_title: "观察对手也会同时行动",
    online_tutorial_step_3_body: "机器人现在会去拿左上角。在线对战是同时进行的，所以你必须时刻看全盘，而不是只盯着自己脚下那一格。",
    online_tutorial_step_4_title: "在正确时机使用冻结",
    online_tutorial_step_4_body: "机器人正在冲右上角。现在点击高亮的冻结技能，把它暂时停住，给自己争取先手。",
    online_tutorial_step_5_title: "进入同一格抢速度",
    online_tutorial_step_5_body: "很好。现在点击发光的右上角，趁机器人还没恢复时赢下这格。多人在线时，同一格会变成正面对速。",
    online_tutorial_step_6_title: "抢夺对手已占的格子",
    online_tutorial_step_6_body: "机器人已经占了左上角。现在点击那个发光的敌方格子，发起一次抢夺。",
    online_tutorial_step_7_title: "防守会把抢夺变成正面对决",
    online_tutorial_step_7_body: "机器人已经防守，所以现在你们会在同一格里正面拼小游戏。注意：当你被偷家时可以点防守，但如果你当前正在冲更关键的格子，也可以选择不防守继续抢节奏。",
    online_tutorial_step_8_title: "教程完成",
    online_tutorial_step_8_body: "你已经体验了在线对战最核心的三件事：抢空格、冻结抢节奏、抢夺并对抗防守。现在可以去打真人了。",
    invite_copy_link: "复制邀请链接",
    invite_link_copied: "\u2713 已复制！",
    game_steal: "抢夺",
    game_enemy: "对手",
    game_you: "你",
    game_ready: "技能就绪",
    game_no_steal: "技能耗尽",
    game_playing: "正在攻克",
    game_rematch: "再来一局",
    game_rematch_request_sent: "已发起再来一局邀请...",
    game_rematch_invite: "对方邀请再来一局",
    game_rematch_accept: "同意",
    game_rematch_decline: "拒绝",
    game_rematch_wait_host: "已同意，等待房主开始...",
    game_rematch_declined: "对方拒绝了再来一局",

    msg_win: "你赢了！",
    msg_lose: "对手获胜！",
    msg_draw: "平局！",
    msg_challenge_complete: "挑战完成！",
    msg_steal_attack: "基地遇袭！",
    msg_steal_doing: "正在偷家...",
    msg_steal_attack_desc: "对手正在偷第 {cell} 格！你可以点“防守”回防；如果当前冲格更关键，也可以不防守继续推进。",
    msg_steal_doing_desc: "正在从对手手里偷第 {cell} 格！",
    msg_defend: "防守",

    rules_title: "游戏规则",
    rules_intro: "GridRush 不是传统的轮流下棋，而是靠更快通关小游戏来抢格子。",
    rules_goal: "任意一方连成三格立即获胜；若 9 格全部占满，则占格更多者获胜。",
    rules_quick_title: "30 秒上手",
    rules_quick_1: "蓝方是 P1，红方是 P2。空格可以直接挑战，对手已占的格子必须靠“抢夺”进入。",
    rules_quick_2: "点击带“?”的格子进入该格小游戏，谁先通关，格子就立刻归谁。",
    rules_quick_3: "双方可以同时挑战不同格子，所以不要只盯着自己当前那一格。",
    rules_quick_4: "你可以随时退出当前挑战，但如果是在抢夺途中放弃，会触发 20 秒抢夺冷却。",
    rules_flow_title: "一局在线对战怎么进行",
    rules_flow_1: "正式开打前，双方会先秘密从 3 个核心技能里选 2 个，这决定你这局能用哪些招。",
    rules_flow_2: "接着进行三局两胜的猜拳，输的一方在棋盘开局时会先被冻结 2 秒。",
    rules_flow_3: "进入棋盘阶段后，小游戏一旦通关成功，对应格子会立刻判给通关者。",
    rules_flow_4: "如果被抢的一方在 5 秒内按下防守，双方就会在同一格正面对决，直到有人先通关。",
    rules_penalty_title: "失败与惩罚",
    rules_penalty_1: "同一格连续失败 3 次，你会被该格禁入 10 秒。",
    rules_penalty_2: "长时间无操作、断线太久，或在同一挑战里停留过久，系统都会把你踢出当前格子。",
    rules_skills_intro: "每局在线对战都会先秘密从 3 个核心技能里选 2 个。",
    rules_steal: "只有这局选到“抢夺”时才能用一次。进入对手已占格会发起抢夺；如果对手及时防守，双方就会争夺同一格。",
    rules_freeze: "只有这局选到“冻结”时才能用一次。它会让对手 2 秒内无法操作。",
    rules_duel: "只有这局选到“决斗”时才能用一次。你可以指定一个空格，强制双方立刻进入同一小游戏，胜者直接拿下该格。",
    rules_fun_title: "娱乐模式",
    rules_fun_desc: "娱乐模式保留正常胜负规则，但每次占格后还可能抽到黑幕、换题、炸弹、翻转等混乱卡牌。",
    rules_tips_title: "新手建议",
    rules_tip_1: "刚上手时先抢中间和角位，稳定拿空格通常比冒险偷家更划算。",
    rules_tip_2: "不要在一个难格上硬磕到第 3 次失败，及时换目标更值。",
    rules_tip_3: "冻结和决斗更适合用来打断对手连线，别一开局就随手交掉。",

    settings_title: "游戏设置",
    settings_lang: "语言 / Language",
    settings_theme: "外观 / Theme",
    settings_sound: "音效",
    settings_music: "背景音乐",
    settings_data: "清除数据",
    settings_data_desc: "重置所有成就和统计数据",
    settings_reset: "重置",
    settings_close: "关闭",

    account_sign_in: "登录",
    account_sign_up: "注册",
    account_create_account: "创建账号",
    account_sign_out: "退出登录",
    account_email: "邮箱",
    account_password: "密码",
    account_nickname: "昵称",
    account_nickname_placeholder: "输入展示昵称",
    account_nickname_too_short: "昵称至少需要 2 个字符。",
    account_guest_desc: "登录后可把统计同步到云端，并在多设备间共用同一账号。",
    account_connected: "云端账号已连接",
    account_local_only: "仅本地",
    account_syncing: "同步中...",
    account_synced: "已同步",
    account_sync_error: "同步失败",
    account_sync_now: "立即同步",
    account_last_sync: "上次同步",
    account_save_profile: "保存资料",
    account_no_nickname: "未命名玩家",
    account_working: "处理中...",
    account_env_missing: "尚未配置 Supabase 环境变量",
    account_env_missing_desc: "把 .env.example 复制为 .env.local，然后填入项目 URL 和 anon key。",
    account_verify_email: "注册请求已提交，请去邮箱完成验证。",
    account_signed_out: "已退出登录，本机本地统计不会被删除。",

    ach_title: "挑战成就",
    ach_locked: "未解锁",
    ach_progress: "进度",

    // 数据面板
    stats_title: "数据统计",
    stats_online_overview: "在线总览",
    stats_online_matches: "在线总场次",
    stats_online_wins: "胜场",
    stats_online_losses: "负场",
    stats_online_draws: "平局",
    stats_rps_title: "猜拳分析",
    stats_rps_round_win_rate: "回合胜率",
    stats_rps_series_win_rate: "整场胜率",
    stats_rps_rounds: "回合胜出",
    stats_rps_series: "整场胜出",
    stats_rps_draws: "平局",
    stats_global_title: "生涯数据",
    stats_games_played: "总对局数",
    stats_best_solo: "竞速最佳",
    stats_ach_unlocked: "已解锁成就",
    stats_practice_records: "练习记录数",
    stats_action_breakdown: "动作分布",
    stats_steals: "抢夺",
    stats_defends: "防守",
    stats_freezes: "冻结",
    stats_duel_wins: "决斗胜利",
    stats_fun_cards_used: "娱乐卡牌使用",
    stats_solo_bests: "竞速难度最佳",
    stats_recent_matches: "最近在线对局",
    stats_recent_empty: "还没有在线对局数据。",
    stats_result_win: "胜",
    stats_result_lose: "负",
    stats_result_draw: "平",
    stats_mode_standard: "标准",
    stats_mode_fun: "娱乐",
    stats_current_streak: "当前连胜",
    stats_recent_trend: "近期走势",
    stats_best_streak: "最高连胜",
    stats_actions_per_match: "每局动作数",
    stats_mode_split: "模式拆分",
    stats_pick_distribution: "出拳分布",
    stats_pick_rock: "石头",
    stats_pick_paper: "布",
    stats_pick_scissors: "剪刀",

    exit_game: "退出",
    level_progress: "关卡",

    // Practice Mode
    prac_search: "搜索小游戏...",
    prac_filter_all: "全部",
    prac_filter_timed: "计时",
    prac_filter_score: "计分",
    prac_filter_accuracy: "准确率",
    prac_pb: "最佳:",
    prac_no_pb: "暂无",
    prac_config_title: "练习设置",
    prac_diff: "难度",
    prac_diff_easy: "简单",
    prac_diff_normal: "普通",
    prac_diff_hard: "困难",
    prac_diff_expert: "专家",
    prac_preset_battle: "对战预设",
    prac_preset_desc: "使用标准在线对战参数",
    prac_tutorial: "教学提示",
    prac_start: "开始练习",
    prac_paused: "已暂停",
    prac_resume: "继续",
    prac_restart: "重开",
    prac_quit: "退出",
    prac_res_success: "挑战完成！",
    prac_res_fail: "挑战失败",
    prac_new_record: "新纪录！",
    prac_history: "最近记录",

    // Skills
    skill_steal: "夺旗",
    skill_freeze: "冻结",
    skill_duel: "决斗",
    skill_used: "已用",
    duel_title: "决斗！",
    duel_pick_instr: "选择一个空格开始决斗 —",
    duel_opp_picking: "对手正在选择格子……",
    duel_racing: "决斗进行中",
    duel_cell: "第",
    skill_pick_title: "选择技能",
    skill_pick_instr: "选择2个带入对局的技能，对方看不到你的选择。",
    skill_pick_confirm: "确认",
    skill_pick_waiting: "等待对手选择……",
    // 猜拳
    rps_title: "猜 拳",
    rps_instr: "三局两胜——赢家提前2秒开始游戏！",
    rps_round: "第",
    rps_you: "你",
    rps_opp: "对手",
    rps_rock: "石头",
    rps_paper: "布",
    rps_scissors: "剪刀",
    rps_you_win: "本局你赢！",
    rps_you_lose: "本局对手赢。",
    rps_draw: "平局！",
    rps_you_picked: "已出招，等待对手……",
    rps_headstart_win: "🎉 你先出发！提前2秒",
    rps_headstart_lose: "对手先出发，准备好！",
    rps_headstart_draw: "平局，同时开始！",
    rps_waiting: "等待对手……",
    // Solo Difficulty Picker
    solo_diff_title: "选择难度",
    solo_diff_instr: "以最快速度按顺序通关全部13个小游戏。",
    solo_diff_easy: "简单",
    solo_diff_normal: "普通",
    solo_diff_hard: "困难",
    solo_diff_expert: "专家",
    solo_diff_desc_easy: "轻松上手，适合新手",
    solo_diff_desc_normal: "适中的技能考验",
    solo_diff_desc_hard: "高难度，失误代价大",
    solo_diff_desc_expert: "非心脏强大者勿入",
    solo_diff_start: "开始挑战",
    solo_diff_back: "返回",
    solo_diff_best: "最佳:",

    // Mode selector
    online_mode_label: "对战模式",
    std_mode: "标准模式",
    std_mode_desc: "经典策略对战，无技能道具。",
    fun_mode: "娱乐模式",
    fun_mode_desc: "每次插旗都能抽到随机道具卡！",

    // Fun mode in-game
    fun_mode_badge: "🎉 娱乐",
    fun_card_drawn: "获得道具！",
    fun_card_use: "使用",
    fun_blinded: "视野被遮挡！",
    fun_flipped: "画面翻转！",
    fun_hard: "噩梦难度！",

    // Fun card names / descriptions
    fun_egg: "黑幕",
    fun_egg_desc: "让对手的棋盘变暗5秒",
    fun_shuffle: "混牌",
    fun_shuffle_desc: "随机打乱所有无主格子的小游戏类型",
    fun_zap: "弹射",
    fun_zap_desc: "把对手踢出当前格子",
    fun_hard_mode: "炼狱",
    fun_hard_mode_desc: "强制对手遭遇专家难度，持续15秒",
    fun_flip: "翻转",
    fun_flip_desc: "让对手的画面翻转5秒",
    fun_bomb: "炸弹",
    fun_bomb_desc: "把对手随机一格夺回成无主格子",
    fun_reroll: "换牌",
    fun_reroll_desc: "把对手当前正在挑战的格子换成随机另一个小游戏",
    fun_leech: "吸附",
    fun_leech_desc: "直接占领一个随机无主格子",
    fun_ice: "冰冻",
    fun_ice_desc: "冻结对手操作3.5秒",
    fun_swap: "置换",
    fun_swap_desc: "将你的一格与对手的一格互换归属",
  }
};

export const ACHIEVEMENTS_LIST: Achievement[] = [
  {
    id: 'first_win',
    titleEn: 'First Blood',
    titleZh: '首战告捷',
    descEn: 'Win your first Online Battle.',
    descZh: '在在线对战中赢得第一次胜利。',
    icon: '🏆',
    condition: (s) => s.onlineWins >= 1
  },
  {
    id: 'speed_demon',
    titleEn: 'Speed Demon',
    titleZh: '极速初体验',
    descEn: 'Complete Time Attack for the first time.',
    descZh: '完成一次竞速模式挑战。',
    icon: '⚡',
    condition: (s) => s.fastestSoloRun > 0
  },
  {
    id: 'thief',
    titleEn: 'Master Thief',
    titleZh: '神偷',
    descEn: 'Successfully steal a cell from an opponent.',
    descZh: '成功从对手手中抢夺一个格子。',
    icon: '🗡️',
    condition: (s) => s.totalSteals >= 1
  },
  {
    id: 'defender',
    titleEn: 'Iron Wall',
    titleZh: '铜墙铁壁',
    descEn: 'Successfully defend your cell from a steal attempt.',
    descZh: '成功防御一次对手的抢夺尝试。',
    icon: '🛡️',
    condition: (s) => s.totalDefends >= 1
  },
  {
    id: 'veteran',
    titleEn: 'Veteran',
    titleZh: '身经百战',
    descEn: 'Play 10 games total.',
    descZh: '总计游玩10局游戏。',
    icon: '🎖️',
    condition: (s) => s.gamesPlayed >= 10
  },
  {
    id: 'dominator',
    titleEn: 'Dominator',
    titleZh: '火力全开',
    descEn: 'Win 5 Online Battles.',
    descZh: '在线对战得胜5局。',
    icon: '💥',
    condition: (s) => s.onlineWins >= 5
  },
  {
    id: 'champion',
    titleEn: 'Champion',
    titleZh: '冠军',
    descEn: 'Win 20 Online Battles.',
    descZh: '在线对战得胜20局。',
    icon: '👑',
    condition: (s) => s.onlineWins >= 20
  },
  {
    id: 'serial_thief',
    titleEn: 'Serial Thief',
    titleZh: '专业山大王',
    descEn: 'Steal 5 cells.',
    descZh: '抢夺对手根5个格子。',
    icon: '🗡️',
    condition: (s) => s.totalSteals >= 5
  },
  {
    id: 'fortress',
    titleEn: 'Fortress',
    titleZh: '山城抽不拼',
    descEn: 'Defend your cells 5 times.',
    descZh: '成功防徣5次对手的抢夺。',
    icon: '🏰',
    condition: (s) => s.totalDefends >= 5
  },
  {
    id: 'lightning',
    titleEn: 'Lightning',
    titleZh: '闪电战神',
    descEn: 'Finish Time Attack on Normal in under 4 minutes.',
    descZh: '在普通难度下4分钟内完成竞速模式。',
    icon: '🌩️',
    condition: (s) => !!s.soloRunsByDiff?.NORMAL && s.soloRunsByDiff.NORMAL < 240000
  },
  {
    id: 'blitz',
    titleEn: 'Blitz',
    titleZh: '急速战神',
    descEn: 'Finish Time Attack on Hard in under 4 minutes.',
    descZh: '在困难难度下4分钟内完成竞速模式。',
    icon: '☄️',
    condition: (s) => !!s.soloRunsByDiff?.HARD && s.soloRunsByDiff.HARD < 240000
  },
  {
    id: 'marathon',
    titleEn: 'Marathon',
    titleZh: '马拉松选手',
    descEn: 'Play 50 games total.',
    descZh: '总计游璁50局。',
    icon: '🏃',
    condition: (s) => s.gamesPlayed >= 50
  },
  {
    id: 'ice_age',
    titleEn: 'Ice Age',
    titleZh: '永冻时代',
    descEn: 'Use the Freeze skill 3 times.',
    descZh: '使用冻结技能 3 次。',
    icon: '❄️',
    condition: (s) => (s.totalFreezes ?? 0) >= 3
  },
  {
    id: 'duel_master',
    titleEn: 'Duel Master',
    titleZh: '决斗王者',
    descEn: 'Win 5 duels.',
    descZh: '在决斗中得胜5次。',
    icon: '⚔️',
    condition: (s) => (s.totalDuelWins ?? 0) >= 5
  },
];